### get
GET http://localhost:10081/hello/world


### post
POST http://localhost:10081/trypost
Content-Type: application/x-www-form-urlencoded

name=doctorwho
&description=timelord


### post json
POST http://localhost:10081/trypostjson
content-type: application/json

{
    "name": "Dr. Who",
    "description":"Time Lord"
}
